Added: basic functionality, readme, example, simle tests
cloudposse/terraform-aws-route53 pull request #2
Opened 2022-05-08 14:18 UTC by vladget

## what
* Describe high-level what changed as a result of these commits (i.e. in plain-english, what do these changes mean?)
* Use bullet points to be concise and to the point.

## why
* Provide the justifications for the changes (e.g. business case). 
* Describe why these changes were made (e.g. why do these commits fix the problem?)
* Use bullet points to be concise and to the point.

## references
* Link to any supporting github issues or helpful documentation to add some context (e.g. stackoverflow). 
* Use `closes #123`, if this PR closes a GitHub issue `#123`

2022-05-09 14:49 UTC, nitrocode commented on examples/complete/main.tf
> +module "zone-route53" {
```suggestion
module "zone_route53" {
```

2022-05-09 14:50 UTC, nitrocode commented on examples/complete/versions.tf
> +      version = "~> 3.0"
We always use greater than signs for module pins

2022-05-09 14:53 UTC, nitrocode commented on main.tf
> +  name          = var.zone_name
Use enabled logic to disable resources

```suggestion
  count = local.enabled ? 1 : 0

  name          = var.zone_name
```

2022-05-09 14:56 UTC, nitrocode commented on versions.tf
> +  required_version = ">= 0.13.0"
Why lower the pin of terraform? Terraform 1.x has been around for a while now

2022-05-09 14:59 UTC, nitrocode commented on test/src/examples_complete_test.go
> +}
Please add a test for when enabled is false

2022-05-09 15:18 UTC, nitrocode commented on examples/complete/versions.tf
> +      version = "~> 3.0"
```suggestion
      version = ">= 3.0"
```

2022-05-09 19:49 UTC, nitrocode commented on README.yaml
> +  module "zone_route53" {
nit

```suggestion
  module "zone" {
```

or

```suggestion
  module "route53_zone" {
```

would read better. Please apply the same change to the example.

2022-05-09 19:49 UTC, nitrocode commented on examples/complete/main.tf
> +module "zone_route53" {
See other comment

2022-05-09 19:50 UTC, nitrocode commented on test/src/examples_complete_test.go
> +  assert.Equal(t, zone_name, zone_name_output)
Can you verify the records as well ?

2022-05-09 19:50 UTC, vladget commented on test/src/examples_complete_test.go
> +}
Here is some strange terraform behavior I cant deal with. Let's add enable/disable functionality to the next version - we need this module ASAP.

2022-05-09 19:53 UTC, nitrocode commented on README.yaml
> -########################################################################################################################
Please run `make init && make pr/readme` to get auto formatting to work correctly

2022-05-09 21:32 UTC, osterman commented on main.tf
> +  # If TTL didn't set and the record type is not an alias - use default TTL
```suggestion
  # If the TTL wasn't set and the record type is not an alias, then use the default TTL
```

2022-05-09 21:36 UTC, osterman commented on main.tf
> +    each.value.type == "TXT" && length(regexall("(\\\"\\\")", r)) == 0 ?
I don't think this regex expresses what it is intended to express.

 What are we trying to do with this regex? `"(\\\"\\\")"`

```suggestion
    each.value.type == "TXT" && length(regexall("(\\\"\\\")", r)) == 0 ?
```

2022-05-09 21:38 UTC, osterman commented on test/src/examples_complete_test.go
> +  assert.Equal(t, zone_name, zone_name_output)
Especially the behavior of txt records, since that has the most complexity

2022-05-09 21:47 UTC, vladget commented on test/src/examples_complete_test.go
> +  assert.Equal(t, zone_name, zone_name_output)
Could we add these tests letter in the next release?
Really need this module asap.

2022-05-09 21:53 UTC, vladget commented on main.tf
> +    each.value.type == "TXT" && length(regexall("(\\\"\\\")", r)) == 0 ?
It is just checking if a record isn't already split.

2022-05-09 21:55 UTC, osterman commented on README.yaml
> +  Route53 module that creates zones and records with various routing policies.
```suggestion
  This terraform module helps manage Route53 zones and associated resource records with various routing policies.
```

2022-05-09 21:55 UTC, osterman commented on main.tf
> +    each.value.type == "TXT" && length(regexall("(\\\"\\\")", r)) == 0 ?
Aha, ok

2022-05-09 21:58 UTC, vladget commented on examples/complete/main.tf
> +module "zone_route53" {
Could you please clarify this comment?

2022-05-09 21:59 UTC, nitrocode commented on examples/complete/main.tf
> +module "zone_route53" {
https://github.com/cloudposse/terraform-aws-route53/pull/2#discussion_r868384002

2022-05-09 22:01 UTC, nitrocode commented on main.tf
> +    each.value.type == "TXT" && length(regexall("(\\\"\\\")", r)) == 0 ?
This could be added as a comment for future contributors

2022-05-09 22:24 UTC, vladget commented on variables.tf
> +  default     = []
we need more complex objects here

2022-05-09 22:27 UTC, osterman commented
/test all

2022-05-09 22:29 UTC, osterman commented
/test all

2022-05-09 22:31 UTC, Nuru requested changes

2022-05-09 22:31 UTC, Nuru commented on main.tf
> +      ])) => {
This is going to fail ("depends on resource attributes that cannot be determined until apply") if `var.records` has any element generated, such as a DKIM key or IP address. 

@osterman I think fundamentally this is part of why we haven't had a module for this before. The resources is not that hard to create directly and the configuration is too complex to pass to a module.

2022-05-09 22:31 UTC, Nuru commented on main.tf
> +      }
Have you verified that this resource works without drift when specifying objects where all members are `null`?

2022-05-09 22:31 UTC, Nuru commented on main.tf
> +    each.value.type == "TXT" && length(regexall("(\\\"\\\")", r)) == 0 ?
@osterman This regex etc. is OK.

2022-05-09 22:31 UTC, Nuru commented on outputs.tf
> +}
```suggestion
}

```

2022-05-09 22:31 UTC, Nuru commented on variables.tf
> +  default     = []
We need documentation of the acceptable values, and type `any` is too vague: at the very least it should be `list(any)`.

More likely we should split it up into several record types, each explicitly defined, something like:
- simple_records
- weighted_records
- geolocated_records
- full_records

@osterman @nitrocode what do you think?

2022-05-09 22:39 UTC, Nuru commented on main.tf
> +    replace(r, "/(.{255})/", "$1\"\"") : r
@vladget @osterman You might consider stripping out newlines. When I was trying to configure DKIM keys, I put the key in a YAML file and split it into 
lines in order to keep the editor from having to deal with a terribly long line. YAML will not completely strip out whitespace between lines, but with the `|` operator will add newlines instead of spaces, so I then stripped the newlines out of the TXT records and was good to go.

```suggestion
    replace(replace(r, "\n",""), "/(.{255})/", "$1\"\"") : r
```

2022-05-10 12:37 UTC, vladget commented on examples/complete/fixtures.us-east-2.tfvars
> +]
It works:

`terraform output
record = {
  "a-record_a" = "a-record.eg-terraform-aws-route53.cloudposse.com"
  "cname-record_cname" = "cname-record.eg-terraform-aws-route53.cloudposse.com"
  "failover-record_cname_failover-record-primary" = "failover-record.eg-terraform-aws-route53.cloudposse.com"
  "failover-record_cname_failover-record-secondary" = "failover-record.eg-terraform-aws-route53.cloudposse.com"
  "geo-record_cname_geo-record-ua" = "geo-record.eg-terraform-aws-route53.cloudposse.com"
  "geo-record_cname_geo-record-us" = "geo-record.eg-terraform-aws-route53.cloudposse.com"
  "txt-record_txt" = "txt-record.eg-terraform-aws-route53.cloudposse.com"
  "weighted-record_cname_weighted-record-10" = "weighted-record.eg-terraform-aws-route53.cloudposse.com"
  "weighted-record_cname_weighted-record-90" = "weighted-record.eg-terraform-aws-route53.cloudposse.com"
}
zone_id = "Z028700125EFEW1B8AIBZ"
zone_name = "eg-terraform-aws-route53.cloudposse.com"`

Let's add all tests at the next release, we need this module asap.

2022-05-10 12:48 UTC, vladget commented on examples/complete/fixtures.us-east-2.tfvars
> +]
Yeap, an object which contains null components is the null component

2022-05-10 23:24 UTC, closed without merging